### PR TITLE
remove demoWorkPlan lwc 

### PR DESCRIPTION
**Pull request by bsugiarto24**

### CODE REVIEW

**Comment by maliroteh-sf** [comment]
@bsugiarto24 looks like you have not signed the CLA yet (see above).

**Comment by bsugiarto24** [comment]
@maliroteh-sf I just signed it.

**Comment by maliroteh-sf** [comment]
@bsugiarto24 There are 2 issues with this PR

1. For some reason it is still showing the CLA as not signed even though you say that you've signed it. Did you log into github and sign the CLA using exactly the same user account that  you've used to open this PR?

2. I don't understand the point of leaving the `lwc` folder behind if you are deleting `demoWorkPlan` and `demoWorkStepPresentation`. After deleting those 2, you're left with `mediumHeaderText` and `staticImage` which don't seem to be used anywhere in the project. So why not just remove the entire `lwc` folder?

**Review by maliroteh-sf — CHANGES_REQUESTED** [review]
@bsugiarto24 There are 2 issues with this PR

1. For some reason it is still showing the CLA as not signed even though you say that you've signed it. Did you log into github and sign the CLA using exactly the same user account that  you've used to open this PR?

2. I don't understand the point of leaving the `lwc` folder behind if you are deleting `demoWorkPlan` and `demoWorkStepPresentation`. After deleting those 2, you're left with `mediumHeaderText` and `staticImage` which don't seem to be used anywhere in the project. So why not just remove the entire `lwc` folder?

**Comment by bsugiarto24** [comment]
@maliroteh-sf 
1. Yes. Not sure what the issue is
2. there's other LWCs that are in the lwc directory so no need to delete the entire directory.

**Review by dongyaoling — APPROVED** [review]

**Comment by maliroteh-sf** [comment]
@dongyaoling @bsugiarto24 can you please explain why `ServiceDocumentSamples` was added to this repo?

When the MPE team decided to open this repo up to other teams to add their LWC samples, the agreement was to add high quality and complete samples. `ServiceDocumentSamples` doesn't meet this bar and I'm not sure why it was added in the first place.

`ServiceDocumentSamples` doesn't have a proper readme (compare it to for example to the readme of `FindNearby`, `FollowUpAppointment`, `MobileDashboard` ...)

Also, as I've already mentioned in my previous comment, if this PR is merged in then you're only left with `mediumHeaderText` and `staticImage` components in the `lwc` folder, which are not used anywhere. So what's the purpose of `mediumHeaderText` and `staticImage` components? and more importantly whats the purpose of `ServiceDocumentSamples` being added to this repo?

If `ServiceDocumentSamples` is still not ready to be shared with external customers then we should remove the entire `ServiceDocumentSamples` and added it back when it is ready (with proper readme and useful components)

CC @khawkins

**Comment by bsugiarto24** [comment]
@maliroteh-sf 
The examples are being used by Service Document customers who want to develop custom lwcs for ServiceDocuments. They follow certain code patterns that allow them to be primable and offlinable. Also our README has a link to the documentation to how these components are used.

Is it ok to merge?

**Pull request merged**
