### PR TITLE
Add lerna support and clean up all projects

### PR DESCRIPTION
**Pull request by maliroteh-sf**

### CODE REVIEW

**Comment by dbreese** [comment]
Huge PR, where should we focus? ;)

**Comment by khawkins** [comment]
I see that only a subset of projects are configured to run tests. I'm presuming that's either because the others didn't have test targets, or their test targets don't work?

**Review by khawkins — APPROVED** [review]
This looks fine to me in the broad details. In the future I'd recommend breaking this up into multiple PRs, to make it easier to review. Even though you're working on a lot of files, there are still ways to minimize the impact of reviewing those changes by breaking them up. For example:

- First PR simply moves all projects under the `projects/` umbrella. No further changes.
- Second PR reformats all files with `prettier`. No further changes.
- (Optional) 3rd to _n_ PRs do the same for any other applicable targets (lint, test, etc.).
- Final PR implements Lerna configuration changes to support the monorepo.

There were a number of changes aggregated in this PR, that would have been more easily reviewed by splitting them out.

Thanks for taking this on! It'll help manage all of the disparate projects a lot more consistently here. 👍

**Comment by maliroteh-sf** [comment]
> I see that only a subset of projects are configured to run tests. I'm presuming that's either because the others didn't have test targets, or their test targets don't work?

Yes some projects do not have tests. We can have follow up PRs to add tests to these sample LWC projects if we want to.

**Pull request merged**
