### PR TITLE
Reschedule Appointment labels & bug fix

### PR DESCRIPTION
**Pull request by ibenitamar**
Renamed custom lables to decouple from Appointment Assistent project labels  Fixed bug: incorrect minValidCalenderDate when changing assignment method

### CODE REVIEW

**Review by maliroteh-sf — COMMENTED** [review]
1. If I run `npm install && npm run lint` I see more than 200 linting error... please invest some time to clean these up.

2. How do you run your unit test? Executing `npm run test` did not run any tests for me... instead I see `No tests found, exiting with code 1` this:
```
$ npm run test

> salesforce-app@1.0.0 test
> npm run test:unit


> salesforce-app@1.0.0 test:unit
> sfdx-lwc-jest

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /Users/maliroteh/Desktop/LWC-Mobile-Samples/RescheduleAppointments
  28 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 0 matches
  testPathIgnorePatterns: /Users/maliroteh/Desktop/LWC-Mobile-Samples/RescheduleAppointments/node_modules/, /Users/maliroteh/Desktop/LWC-Mobile-Samples/RescheduleAppointments/test/specs/ - 28 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches
```

**Comment by maliroteh-sf** [comment]
> @maliroteh-sf We had a few discussions about this inherited code linting errors, I think you saw for yourself that fixing those caused a lot of bugs. The ones with no effect were fixed here #33 and the rest can be discussed since it's a process and will take time, but I don't think it should be discussed in every PR. Unit Tests will be added during 246 it's currently only tested manually.

Can you please share the `W-` work item that you're using for tracking these linting issues? I know I've raised this issue in the past but it is easy to forget it or not prioritize it if there is no work item tracking it.

FYI, in early 246 (in the next few weeks) we plan on adding `lerna` to this repo and update our CI to run formatting+linting +unit test checks `for each incoming PR` and if any of those fails then the PR will not be merged. This means that if your team doesn't fix these linting issues soon, once we update our CI process, your future PRs will not be accepted until these issues are resolved first. Something for you to discuss with your team to allocate some time for investigating & resolving these linting issues.

CC @khawkins

**Comment by ibenitamar** [comment]
@maliroteh-sf OK I'll take this to my manager and PM to prioritize thanks!

**Review by maliroteh-sf — APPROVED** [review]

**Review by khawkins — APPROVED** [review]
In addition to @maliroteh-sf 's clean-up comments, it'd be good to check in `package-lock.json` (presuming the project went with npm over yarn), as it's meant to be persisted in source control.

Overall, this looks fine. But I agree with Meisam, that we need to get a baseline of functioning code maintenance tools working OOTB here, including tests, linting, and prettier checks. There will be forcing functions for this in the future.

**Pull request merged**
